export enum IconFilledCategories {
  ACTION = 'filled-action',
  ALERT = 'filled-alert',
  AV = 'filled-av',
  COMMUNICATION = 'filled-communication',
  CONTENT = 'filled-content',
  DEVICE = 'filled-device',
  EDITOR = 'filled-editor',
  FILE = 'filled-file',
  HARDWARE = 'filled-hardware',
  HOME = 'filled-home',
  IMAGE = 'filled-image',
  MAPS = 'filled-maps',
  NAVIGATION = 'filled-navigation',
  NOTIFICATION = 'filled-notification',
  PLACES = 'filled-places',
  SOCIAL = 'filled-social',
  TOGGLE = 'filled-toggle',
}

export enum IconOutlinedCategories {
  ACTION = 'outlined-action',
  ALERT = 'outlined-alert',
  AV = 'outlined-av',
  COMMUNICATION = 'outlined-communication',
  CONTENT = 'outlined-content',
  DEVICE = 'outlined-device',
  EDITOR = 'outlined-editor',
  FILE = 'outlined-file',
  HARDWARE = 'outlined-hardware',
  HOME = 'outlined-home',
  IMAGE = 'outlined-image',
  MAPS = 'outlined-maps',
  NAVIGATION = 'outlined-navigation',
  NOTIFICATION = 'outlined-notification',
  PLACES = 'outlined-places',
  SOCIAL = 'outlined-social',
  TOGGLE = 'outlined-toggle',
}
